version: '3.3'

#name: mongodb-forum
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: airboyforum
      MONGO_INITDB_ROOT_PASSWORD: admin

networks:
  default:
    external: true
    name: api
